FROM tensorflow/tensorflow:2.4.1-gpu-jupyter

ARG APP_HOME=/opt/program

# Setup the environment path
ENV PATH="${APP_HOME}:${PATH}"

ARG PYTHON=python3
ARG PYTHON_PIP=python3-pip
ARG PIP=pip3

RUN ${PIP} --no-cache-dir install --upgrade pip

COPY src ${APP_HOME}

RUN ${PIP} install -r ${APP_HOME}/requirements.txt

WORKDIR ${APP_HOME}

ENTRYPOINT ["python3", "train.py"]